# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
