# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, upload_to='badge-images/'),
        ),
    ]
