# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_auto_20170622_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='badge',
        ),
        migrations.AddField(
            model_name='badge',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
