# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_auto_20170622_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='brief',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
