# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_badge_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
