# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_auto_20170628_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgePrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_badge_status', models.IntegerField(choices=[(0, 'Started'), (1, 'Needs Approval'), (2, 'Earned')], default=2)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereqs', to='badges.Badge')),
                ('required_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_set', to='badges.Badge')),
            ],
        ),
    ]
